import cv2
import albumentations as A


height = 384
width = int(height / 0.7586206896551724)

if width % 2 == 1:
    width += 1

augs = {
    'baseline': A.Compose([
        # A.CLAHE( clip_limit=4.0,
        #          tile_grid_size=(8, 8), 
        #          p=0.33 ),
        A.Flip(p=0.75),
        A.OneOf(
            [ A.Sharpen( p=0.5 ),
#               A.Blur ( blur_limit=5,
#                        p=0.16 ),
              A.GaussianBlur( blur_limit=(3, 7),
                              sigma_limit=0,
                              p=0.5 ),
            #   A.GlassBlur( sigma=0.7,
            #                max_delta=4,
            #                iterations=1,
            #                mode='fast',
            #                p=0.16),
            #   A.MedianBlur( blur_limit=7,
            #                 p=0.16 ),
            #   A.MotionBlur( blur_limit=7,
            #                 p=0.16 ) # ? 
            ], p=0.32),
        A.ShiftScaleRotate( shift_limit=0.03,
                            scale_limit=0.0,
                            rotate_limit=10,
                            interpolation=cv2.INTER_CUBIC,
                            border_mode=cv2.BORDER_CONSTANT,
                            value=0,
                            mask_value=0,
                            p=0.5 ),
#         A.HueSaturationValue( hue_shift_limit=20,
#                               sat_shift_limit=0,
#                               val_shift_limit=0, 
#                               p=0.5 ),
        A.Resize( height=height, 
                  width=width, 
                  p=1. ),
        A.ChannelShuffle(p=0.83),
        A.Solarize( threshold=128, p=0.16 ),
        A.InvertImg(p=0.16),
        A.ToGray(p=0.16),
        A.OneOf(
            [ A.Cutout( num_holes=8,
                        max_h_size=int(height*0.015),
                        max_w_size=int(width*0.015),
                        fill_value=0, 
                        p=0.5 ),
              A.PixelDropout( dropout_prob=0.01,
                              per_channel=False,
                              drop_value=0,
                              mask_drop_value=0,
                              p=0.5)
            ], p=0.32),
    ]),
    'invert_p50': A.Compose([
        A.Flip(p=0.75),
        A.OneOf(
            [ A.Sharpen( p=0.5 ),
              A.GaussianBlur( blur_limit=(3, 7),
                              sigma_limit=0,
                              p=0.5 ),
            ], p=0.32),
        A.ShiftScaleRotate( shift_limit=0.03,
                            scale_limit=0.0,
                            rotate_limit=10,
                            interpolation=cv2.INTER_CUBIC,
                            border_mode=cv2.BORDER_CONSTANT,
                            value=0,
                            mask_value=0,
                            p=0.5 ),
        A.Resize( height=height, 
                  width=width, 
                  p=1. ),
        A.ChannelShuffle(p=0.83),
        A.Solarize( threshold=128, p=0.16 ),
        A.InvertImg(p=0.50),
        A.ToGray(p=0.16),
        A.OneOf(
            [ A.Cutout( num_holes=8,
                        max_h_size=int(height*0.015),
                        max_w_size=int(width*0.015),
                        fill_value=0, 
                        p=0.5 ),
              A.PixelDropout( dropout_prob=0.01,
                              per_channel=False,
                              drop_value=0,
                              mask_drop_value=0,
                              p=0.5)
            ], p=0.32),
    ]),
    'solarize_p50': A.Compose([
        A.Flip(p=0.75),
        A.OneOf(
            [ A.Sharpen( p=0.5 ),
              A.GaussianBlur( blur_limit=(3, 7),
                              sigma_limit=0,
                              p=0.5 ),
            ], p=0.32),
        A.ShiftScaleRotate( shift_limit=0.03,
                            scale_limit=0.0,
                            rotate_limit=10,
                            interpolation=cv2.INTER_CUBIC,
                            border_mode=cv2.BORDER_CONSTANT,
                            value=0,
                            mask_value=0,
                            p=0.5 ),
        A.Resize( height=height, 
                  width=width, 
                  p=1. ),
        A.ChannelShuffle(p=0.83),
        A.Solarize( threshold=128, p=0.50 ),
        A.InvertImg(p=0.16),
        A.ToGray(p=0.16),
        A.OneOf(
            [ A.Cutout( num_holes=8,
                        max_h_size=int(height*0.015),
                        max_w_size=int(width*0.015),
                        fill_value=0, 
                        p=0.5 ),
              A.PixelDropout( dropout_prob=0.01,
                              per_channel=False,
                              drop_value=0,
                              mask_drop_value=0,
                              p=0.5)
            ], p=0.32),
    ]),
    'clahe_p16': A.Compose([
        A.CLAHE( clip_limit=4.0,
                 tile_grid_size=(8, 8), 
                 p=0.16 ),
        A.Flip(p=0.75),
        A.OneOf(
            [ A.Sharpen( p=0.5 ),
#               A.Blur ( blur_limit=5,
#                        p=0.16 ),
              A.GaussianBlur( blur_limit=(3, 7),
                              sigma_limit=0,
                              p=0.5 ),
            #   A.GlassBlur( sigma=0.7,
            #                max_delta=4,
            #                iterations=1,
            #                mode='fast',
            #                p=0.16),
            #   A.MedianBlur( blur_limit=7,
            #                 p=0.16 ),
            #   A.MotionBlur( blur_limit=7,
            #                 p=0.16 ) # ? 
            ], p=0.32),
        A.ShiftScaleRotate( shift_limit=0.03,
                            scale_limit=0.0,
                            rotate_limit=10,
                            interpolation=cv2.INTER_CUBIC,
                            border_mode=cv2.BORDER_CONSTANT,
                            value=0,
                            mask_value=0,
                            p=0.5 ),
#         A.HueSaturationValue( hue_shift_limit=20,
#                               sat_shift_limit=0,
#                               val_shift_limit=0, 
#                               p=0.5 ),
        A.Resize( height=height, 
                  width=width, 
                  p=1. ),
        A.ChannelShuffle(p=0.83),
        A.Solarize( threshold=128, p=0.16 ),
        A.InvertImg(p=0.16),
        A.ToGray(p=0.16),
        A.OneOf(
            [ A.Cutout( num_holes=8,
                        max_h_size=int(height*0.015),
                        max_w_size=int(width*0.015),
                        fill_value=0, 
                        p=0.5 ),
              A.PixelDropout( dropout_prob=0.01,
                              per_channel=False,
                              drop_value=0,
                              mask_drop_value=0,
                              p=0.5)
            ], p=0.32),
    ]),
    'equalize_p16': A.Compose([
        A.Equalize (mode='cv', by_channels=True, mask=None, mask_params=(), always_apply=False, p=0.16),
        A.Flip(p=0.75),
        A.OneOf(
            [ A.Sharpen( p=0.5 ),
#               A.Blur ( blur_limit=5,
#                        p=0.16 ),
              A.GaussianBlur( blur_limit=(3, 7),
                              sigma_limit=0,
                              p=0.5 ),
            #   A.GlassBlur( sigma=0.7,
            #                max_delta=4,
            #                iterations=1,
            #                mode='fast',
            #                p=0.16),
            #   A.MedianBlur( blur_limit=7,
            #                 p=0.16 ),
            #   A.MotionBlur( blur_limit=7,
            #                 p=0.16 ) # ? 
            ], p=0.32),
        A.ShiftScaleRotate( shift_limit=0.03,
                            scale_limit=0.0,
                            rotate_limit=10,
                            interpolation=cv2.INTER_CUBIC,
                            border_mode=cv2.BORDER_CONSTANT,
                            value=0,
                            mask_value=0,
                            p=0.5 ),
#         A.HueSaturationValue( hue_shift_limit=20,
#                               sat_shift_limit=0,
#                               val_shift_limit=0, 
#                               p=0.5 ),
        A.Resize( height=height, 
                  width=width, 
                  p=1. ),
        A.ChannelShuffle(p=0.83),
        A.Solarize( threshold=128, p=0.16 ),
        A.InvertImg(p=0.16),
        A.ToGray(p=0.16),
        A.OneOf(
            [ A.Cutout( num_holes=8,
                        max_h_size=int(height*0.015),
                        max_w_size=int(width*0.015),
                        fill_value=0, 
                        p=0.5 ),
              A.PixelDropout( dropout_prob=0.01,
                              per_channel=False,
                              drop_value=0,
                              mask_drop_value=0,
                              p=0.5)
            ], p=0.32),
    ]),
    'brightness_p16': A.Compose([
        A.RandomBrightnessContrast (brightness_limit=0.2, contrast_limit=0.2, brightness_by_max=True, always_apply=False, p=0.16),
        A.Flip(p=0.75),
        A.OneOf(
            [ A.Sharpen( p=0.5 ),
#               A.Blur ( blur_limit=5,
#                        p=0.16 ),
              A.GaussianBlur( blur_limit=(3, 7),
                              sigma_limit=0,
                              p=0.5 ),
            #   A.GlassBlur( sigma=0.7,
            #                max_delta=4,
            #                iterations=1,
            #                mode='fast',
            #                p=0.16),
            #   A.MedianBlur( blur_limit=7,
            #                 p=0.16 ),
            #   A.MotionBlur( blur_limit=7,
            #                 p=0.16 ) # ? 
            ], p=0.32),
        A.ShiftScaleRotate( shift_limit=0.03,
                            scale_limit=0.0,
                            rotate_limit=10,
                            interpolation=cv2.INTER_CUBIC,
                            border_mode=cv2.BORDER_CONSTANT,
                            value=0,
                            mask_value=0,
                            p=0.5 ),
#         A.HueSaturationValue( hue_shift_limit=20,
#                               sat_shift_limit=0,
#                               val_shift_limit=0, 
#                               p=0.5 ),
        A.Resize( height=height, 
                  width=width, 
                  p=1. ),
        A.ChannelShuffle(p=0.83),
        A.Solarize( threshold=128, p=0.16 ),
        A.InvertImg(p=0.16),
        A.ToGray(p=0.16),
        A.OneOf(
            [ A.Cutout( num_holes=8,
                        max_h_size=int(height*0.015),
                        max_w_size=int(width*0.015),
                        fill_value=0, 
                        p=0.5 ),
              A.PixelDropout( dropout_prob=0.01,
                              per_channel=False,
                              drop_value=0,
                              mask_drop_value=0,
                              p=0.5)
            ], p=0.32),
    ]),
    'tone_p16': A.Compose([
        A.RandomToneCurve (scale=0.1, always_apply=False, p=0.16),
        A.Flip(p=0.75),
        A.OneOf(
            [ A.Sharpen( p=0.5 ),
#               A.Blur ( blur_limit=5,
#                        p=0.16 ),
              A.GaussianBlur( blur_limit=(3, 7),
                              sigma_limit=0,
                              p=0.5 ),
            #   A.GlassBlur( sigma=0.7,
            #                max_delta=4,
            #                iterations=1,
            #                mode='fast',
            #                p=0.16),
            #   A.MedianBlur( blur_limit=7,
            #                 p=0.16 ),
            #   A.MotionBlur( blur_limit=7,
            #                 p=0.16 ) # ? 
            ], p=0.32),
        A.ShiftScaleRotate( shift_limit=0.03,
                            scale_limit=0.0,
                            rotate_limit=10,
                            interpolation=cv2.INTER_CUBIC,
                            border_mode=cv2.BORDER_CONSTANT,
                            value=0,
                            mask_value=0,
                            p=0.5 ),
#         A.HueSaturationValue( hue_shift_limit=20,
#                               sat_shift_limit=0,
#                               val_shift_limit=0, 
#                               p=0.5 ),
        A.Resize( height=height, 
                  width=width, 
                  p=1. ),
        A.ChannelShuffle(p=0.83),
        A.Solarize( threshold=128, p=0.16 ),
        A.InvertImg(p=0.16),
        A.ToGray(p=0.16),
        A.OneOf(
            [ A.Cutout( num_holes=8,
                        max_h_size=int(height*0.015),
                        max_w_size=int(width*0.015),
                        fill_value=0, 
                        p=0.5 ),
              A.PixelDropout( dropout_prob=0.01,
                              per_channel=False,
                              drop_value=0,
                              mask_drop_value=0,
                              p=0.5)
            ], p=0.32),
    ]),
    'composite': A.Compose([
        # A.CLAHE( clip_limit=4.0,
        #          tile_grid_size=(8, 8), 
        #          p=0.33 ),
        A.Flip(p=0.75),
        A.OneOf(
            [ A.Sharpen( p=0.5 ),
#               A.Blur ( blur_limit=5,
#                        p=0.16 ),
              A.GaussianBlur( blur_limit=(3, 7),
                              sigma_limit=0,
                              p=0.5 ),
            #   A.GlassBlur( sigma=0.7,
            #                max_delta=4,
            #                iterations=1,
            #                mode='fast',
            #                p=0.16),
            #   A.MedianBlur( blur_limit=7,
            #                 p=0.16 ),
            #   A.MotionBlur( blur_limit=7,
            #                 p=0.16 ) # ? 
            ], p=0.32),
        A.ShiftScaleRotate( shift_limit=0.03,
                            scale_limit=0.0,
                            rotate_limit=10,
                            interpolation=cv2.INTER_CUBIC,
                            border_mode=cv2.BORDER_CONSTANT,
                            value=0,
                            mask_value=0,
                            p=0.5 ),
#         A.HueSaturationValue( hue_shift_limit=20,
#                               sat_shift_limit=0,
#                               val_shift_limit=0, 
#                               p=0.5 ),
        A.Resize( height=height, 
                  width=width, 
                  p=1. ),
        A.ChannelShuffle(p=0.83),
        A.Solarize( threshold=128, p=0.16 ),
        A.InvertImg(p=0.16),
        A.ToGray(p=0.16),
        A.OneOf(
            [ A.Cutout( num_holes=8,
                        max_h_size=int(height*0.015),
                        max_w_size=int(width*0.015),
                        fill_value=0, 
                        p=0.5 ),
              A.PixelDropout( dropout_prob=0.01,
                              per_channel=False,
                              drop_value=0,
                              mask_drop_value=0,
                              p=0.5)
            ], p=0.32),
    ]),
    'dropout_p16': A.Compose([
        # A.CLAHE( clip_limit=4.0,
        #          tile_grid_size=(8, 8), 
        #          p=0.33 ),
        A.Flip(p=0.75),
        A.OneOf(
            [ A.Sharpen( p=0.5 ),
#               A.Blur ( blur_limit=5,
#                        p=0.16 ),
              A.GaussianBlur( blur_limit=(3, 7),
                              sigma_limit=0,
                              p=0.5 ),
            #   A.GlassBlur( sigma=0.7,
            #                max_delta=4,
            #                iterations=1,
            #                mode='fast',
            #                p=0.16),
            #   A.MedianBlur( blur_limit=7,
            #                 p=0.16 ),
            #   A.MotionBlur( blur_limit=7,
            #                 p=0.16 ) # ? 
            ], p=0.32),
        A.ShiftScaleRotate( shift_limit=0.03,
                            scale_limit=0.0,
                            rotate_limit=10,
                            interpolation=cv2.INTER_CUBIC,
                            border_mode=cv2.BORDER_CONSTANT,
                            value=0,
                            mask_value=0,
                            p=0.5 ),
#         A.HueSaturationValue( hue_shift_limit=20,
#                               sat_shift_limit=0,
#                               val_shift_limit=0, 
#                               p=0.5 ),
        A.Resize( height=height, 
                  width=width, 
                  p=1. ),
        A.ChannelDropout( channel_drop_range=(1, 1), fill_value=0, p=0.16 ),
        A.ChannelShuffle(p=0.83),
        A.Solarize( threshold=128, p=0.16 ),
        A.InvertImg(p=0.16),
        A.ToGray(p=0.16),
        A.OneOf(
            [ A.Cutout( num_holes=8,
                        max_h_size=int(height*0.015),
                        max_w_size=int(width*0.015),
                        fill_value=0, 
                        p=0.5 ),
              A.PixelDropout( dropout_prob=0.01,
                              per_channel=False,
                              drop_value=0,
                              mask_drop_value=0,
                              p=0.5)
            ], p=0.32),
    ]),
    'hsv_p16': A.Compose([
        A.HueSaturationValue (hue_shift_limit=20, sat_shift_limit=30, val_shift_limit=20, always_apply=False, p=0.16),
        # A.CLAHE( clip_limit=4.0,
        #          tile_grid_size=(8, 8), 
        #          p=0.33 ),
        A.Flip(p=0.75),
        A.OneOf(
            [ A.Sharpen( p=0.5 ),
#               A.Blur ( blur_limit=5,
#                        p=0.16 ),
              A.GaussianBlur( blur_limit=(3, 7),
                              sigma_limit=0,
                              p=0.5 ),
            #   A.GlassBlur( sigma=0.7,
            #                max_delta=4,
            #                iterations=1,
            #                mode='fast',
            #                p=0.16),
            #   A.MedianBlur( blur_limit=7,
            #                 p=0.16 ),
            #   A.MotionBlur( blur_limit=7,
            #                 p=0.16 ) # ? 
            ], p=0.32),
        A.ShiftScaleRotate( shift_limit=0.03,
                            scale_limit=0.0,
                            rotate_limit=10,
                            interpolation=cv2.INTER_CUBIC,
                            border_mode=cv2.BORDER_CONSTANT,
                            value=0,
                            mask_value=0,
                            p=0.5 ),
#         A.HueSaturationValue( hue_shift_limit=20,
#                               sat_shift_limit=0,
#                               val_shift_limit=0, 
#                               p=0.5 ),
        A.Resize( height=height, 
                  width=width, 
                  p=1. ),
        A.ChannelShuffle(p=0.83),
        A.Solarize( threshold=128, p=0.16 ),
        A.InvertImg(p=0.16),
        A.ToGray(p=0.16),
        A.OneOf(
            [ A.Cutout( num_holes=8,
                        max_h_size=int(height*0.015),
                        max_w_size=int(width*0.015),
                        fill_value=0, 
                        p=0.5 ),
              A.PixelDropout( dropout_prob=0.01,
                              per_channel=False,
                              drop_value=0,
                              mask_drop_value=0,
                              p=0.5)
            ], p=0.32),
    ]),
    'rgbshift_p16': A.Compose([
        A.RGBShift( r_shift_limit=20, g_shift_limit=20,  b_shift_limit=20, p=0.16 ),
        # A.CLAHE( clip_limit=4.0,
        #          tile_grid_size=(8, 8), 
        #          p=0.33 ),
        A.Flip(p=0.75),
        A.OneOf(
            [ A.Sharpen( p=0.5 ),
#               A.Blur ( blur_limit=5,
#                        p=0.16 ),
              A.GaussianBlur( blur_limit=(3, 7),
                              sigma_limit=0,
                              p=0.5 ),
            #   A.GlassBlur( sigma=0.7,
            #                max_delta=4,
            #                iterations=1,
            #                mode='fast',
            #                p=0.16),
            #   A.MedianBlur( blur_limit=7,
            #                 p=0.16 ),
            #   A.MotionBlur( blur_limit=7,
            #                 p=0.16 ) # ? 
            ], p=0.32),
        A.ShiftScaleRotate( shift_limit=0.03,
                            scale_limit=0.0,
                            rotate_limit=10,
                            interpolation=cv2.INTER_CUBIC,
                            border_mode=cv2.BORDER_CONSTANT,
                            value=0,
                            mask_value=0,
                            p=0.5 ),
#         A.HueSaturationValue( hue_shift_limit=20,
#                               sat_shift_limit=0,
#                               val_shift_limit=0, 
#                               p=0.5 ),
        A.Resize( height=height, 
                  width=width, 
                  p=1. ),
        A.ChannelShuffle(p=0.83),
        A.Solarize( threshold=128, p=0.16 ),
        A.InvertImg(p=0.16),
        A.ToGray(p=0.16),
        A.OneOf(
            [ A.Cutout( num_holes=8,
                        max_h_size=int(height*0.015),
                        max_w_size=int(width*0.015),
                        fill_value=0, 
                        p=0.5 ),
              A.PixelDropout( dropout_prob=0.01,
                              per_channel=False,
                              drop_value=0,
                              mask_drop_value=0,
                              p=0.5)
            ], p=0.32),
    ]),
 'blur_p16': A.Compose([
        # A.CLAHE( clip_limit=4.0,
        #          tile_grid_size=(8, 8), 
        #          p=0.33 ),
        A.Flip(p=0.75),
        A.OneOf(
            [ A.Sharpen( p=0.5 ),
              A.Blur ( blur_limit=5,
                       p=0.5 ),
              A.GaussianBlur( blur_limit=(3, 7),
                              sigma_limit=0,
                              p=0.5 ),
            #   A.GlassBlur( sigma=0.7,
            #                max_delta=4,
            #                iterations=1,
            #                mode='fast',
            #                p=0.16),
            #   A.MedianBlur( blur_limit=7,
            #                 p=0.16 ),
            #   A.MotionBlur( blur_limit=7,
            #                 p=0.16 ) # ? 
            ], p=0.48),
        A.ShiftScaleRotate( shift_limit=0.03,
                            scale_limit=0.0,
                            rotate_limit=10,
                            interpolation=cv2.INTER_CUBIC,
                            border_mode=cv2.BORDER_CONSTANT,
                            value=0,
                            mask_value=0,
                            p=0.5 ),
#         A.HueSaturationValue( hue_shift_limit=20,
#                               sat_shift_limit=0,
#                               val_shift_limit=0, 
#                               p=0.5 ),
        A.Resize( height=height, 
                  width=width, 
                  p=1. ),
        A.ChannelShuffle(p=0.83),
        A.Solarize( threshold=128, p=0.16 ),
        A.InvertImg(p=0.16),
        A.ToGray(p=0.16),
        A.OneOf(
            [ A.Cutout( num_holes=8,
                        max_h_size=int(height*0.015),
                        max_w_size=int(width*0.015),
                        fill_value=0, 
                        p=0.5 ),
              A.PixelDropout( dropout_prob=0.01,
                              per_channel=False,
                              drop_value=0,
                              mask_drop_value=0,
                              p=0.5)
            ], p=0.32),
    ]),
 'superpixel_p16': A.Compose([
     A.Superpixels (p_replace=0.1, n_segments=100, max_size=128, interpolation=1, always_apply=False, p=0.16),
        # A.CLAHE( clip_limit=4.0,
        #          tile_grid_size=(8, 8), 
        #          p=0.33 ),
        A.Flip(p=0.75),
        A.OneOf(
            [ A.Sharpen( p=0.5 ),
            #   A.Blur ( blur_limit=5,
            #            p=0.5 ),
              A.GaussianBlur( blur_limit=(3, 7),
                              sigma_limit=0,
                              p=0.5 ),
            #   A.GlassBlur( sigma=0.7,
            #                max_delta=4,
            #                iterations=1,
            #                mode='fast',
            #                p=0.16),
            #   A.MedianBlur( blur_limit=7,
            #                 p=0.16 ),
            #   A.MotionBlur( blur_limit=7,
            #                 p=0.16 ) # ? 
            ], p=0.32),
        A.ShiftScaleRotate( shift_limit=0.03,
                            scale_limit=0.0,
                            rotate_limit=10,
                            interpolation=cv2.INTER_CUBIC,
                            border_mode=cv2.BORDER_CONSTANT,
                            value=0,
                            mask_value=0,
                            p=0.5 ),
#         A.HueSaturationValue( hue_shift_limit=20,
#                               sat_shift_limit=0,
#                               val_shift_limit=0, 
#                               p=0.5 ),
        A.Resize( height=height, 
                  width=width, 
                  p=1. ),
        A.ChannelShuffle(p=0.83),
        A.Solarize( threshold=128, p=0.16 ),
        A.InvertImg(p=0.16),
        A.ToGray(p=0.16),
        A.OneOf(
            [ A.Cutout( num_holes=8,
                        max_h_size=int(height*0.015),
                        max_w_size=int(width*0.015),
                        fill_value=0, 
                        p=0.5 ),
              A.PixelDropout( dropout_prob=0.01,
                              per_channel=False,
                              drop_value=0,
                              mask_drop_value=0,
                              p=0.5)
            ], p=0.32),
    ]),
        'summury': A.Compose([
        A.RandomBrightnessContrast (brightness_limit=0.2, contrast_limit=0.2, brightness_by_max=True, always_apply=False, p=0.16),
        A.RGBShift( r_shift_limit=20, g_shift_limit=20,  b_shift_limit=20, p=0.16 ),
        # A.CLAHE( clip_limit=4.0,
        #          tile_grid_size=(8, 8), 
        #          p=0.33 ),
        A.Flip(p=0.75),
        A.OneOf(
            [ A.Sharpen( p=0.5 ),
#               A.Blur ( blur_limit=5,
#                        p=0.16 ),
              A.GaussianBlur( blur_limit=(3, 7),
                              sigma_limit=0,
                              p=0.5 ),
            #   A.GlassBlur( sigma=0.7,
            #                max_delta=4,
            #                iterations=1,
            #                mode='fast',
            #                p=0.16),
            #   A.MedianBlur( blur_limit=7,
            #                 p=0.16 ),
            #   A.MotionBlur( blur_limit=7,
            #                 p=0.16 ) # ? 
            ], p=0.32),
        A.ShiftScaleRotate( shift_limit=0.03,
                            scale_limit=0.0,
                            rotate_limit=10,
                            interpolation=cv2.INTER_CUBIC,
                            border_mode=cv2.BORDER_CONSTANT,
                            value=0,
                            mask_value=0,
                            p=0.5 ),
#         A.HueSaturationValue( hue_shift_limit=20,
#                               sat_shift_limit=0,
#                               val_shift_limit=0, 
#                               p=0.5 ),
        A.Resize( height=height, 
                  width=width, 
                  p=1. ),
        A.ChannelDropout( channel_drop_range=(1, 1), fill_value=0, p=0.16 ),
        A.ChannelShuffle(p=0.83),
        A.Solarize( threshold=128, p=0.16 ),
        A.InvertImg(p=0.16),
        A.ToGray(p=0.16),
        A.OneOf(
            [ A.Cutout( num_holes=8,
                        max_h_size=int(height*0.015),
                        max_w_size=int(width*0.015),
                        fill_value=0, 
                        p=0.5 ),
              A.PixelDropout( dropout_prob=0.01,
                              per_channel=False,
                              drop_value=0,
                              mask_drop_value=0,
                              p=0.5)
            ], p=0.32),
    ]),
}